// AUTO-GENERATED by scripts/generateMessages.ts — do not edit by hand.
// Regenerate with `yarn gen:messages` (runs automatically on prebuild, and
// lint-staged regenerates it when messages/*.json change).
// messagesManifest.test.ts fails if this drifts from the message files.
import type { SupportedLocale } from './catalog';

export const MESSAGES_CATALOG: Record<
  SupportedLocale,
  { url: string; hash: string }
> = {
  en: { url: '/messages/en.309ad1bead.json', hash: '309ad1bead' },
  es: { url: '/messages/es.9d1664ef24.json', hash: '9d1664ef24' },
  fr: { url: '/messages/fr.e5f0d96aac.json', hash: 'e5f0d96aac' },
  uk: { url: '/messages/uk.92ec695d1d.json', hash: '92ec695d1d' },
  de: { url: '/messages/de.ced5f1cc51.json', hash: 'ced5f1cc51' },
  pl: { url: '/messages/pl.634acd9ffe.json', hash: '634acd9ffe' },
  it: { url: '/messages/it.a80377159d.json', hash: 'a80377159d' },
  gr: { url: '/messages/gr.573b83b02b.json', hash: '573b83b02b' },
  pt: { url: '/messages/pt.1a77e800a5.json', hash: '1a77e800a5' },
};
