// AUTO-GENERATED by scripts/generateMessages.ts — do not edit by hand.
// Regenerate with `yarn gen:messages` (runs automatically on prebuild, and
// lint-staged regenerates it when messages/*.json change).
// messagesManifest.test.ts fails if this drifts from the message files.
import type { SupportedLocale } from './catalog';

export const MESSAGES_CATALOG: Record<
  SupportedLocale,
  { url: string; hash: string }
> = {
  en: { url: '/messages/en.12c4650728.json', hash: '12c4650728' },
  es: { url: '/messages/es.251305517f.json', hash: '251305517f' },
  fr: { url: '/messages/fr.c800317898.json', hash: 'c800317898' },
  uk: { url: '/messages/uk.fb9adf1a80.json', hash: 'fb9adf1a80' },
  de: { url: '/messages/de.977782121d.json', hash: '977782121d' },
  pl: { url: '/messages/pl.c14874b567.json', hash: 'c14874b567' },
  it: { url: '/messages/it.1f3dd6dfc2.json', hash: '1f3dd6dfc2' },
  gr: { url: '/messages/gr.12634f6587.json', hash: '12634f6587' },
  pt: { url: '/messages/pt.8402abbc4e.json', hash: '8402abbc4e' },
};
