// AUTO-GENERATED by scripts/generateMessages.ts — do not edit by hand.
// Regenerate with `yarn gen:messages` (runs automatically on prebuild, and
// lint-staged regenerates it when messages/*.json change).
// messagesManifest.test.ts fails if this drifts from the message files.
import type { SupportedLocale } from './catalog';

export const MESSAGES_CATALOG: Record<
  SupportedLocale,
  { url: string; hash: string }
> = {
  en: { url: '/messages/en.5bdfa25a20.json', hash: '5bdfa25a20' },
  es: { url: '/messages/es.7908f48e4c.json', hash: '7908f48e4c' },
  fr: { url: '/messages/fr.bc906d147d.json', hash: 'bc906d147d' },
  uk: { url: '/messages/uk.92c6a65286.json', hash: '92c6a65286' },
  de: { url: '/messages/de.33811981f3.json', hash: '33811981f3' },
  pl: { url: '/messages/pl.c9ffc8113c.json', hash: 'c9ffc8113c' },
  it: { url: '/messages/it.742c00ee3a.json', hash: '742c00ee3a' },
  gr: { url: '/messages/gr.34f64d2ee9.json', hash: '34f64d2ee9' },
  pt: { url: '/messages/pt.1dd9056891.json', hash: '1dd9056891' },
};
