/**
 * Interface accents, GENERATED by the Palette Lab (`/dev/palette-lab`, dev
 * server only): pick there, press "Copy as TS" and replace this file. Hand
 * edits are fine as long as the shape stays the same.
 *
 * Values are OKLCH: h = hue (deg), l = lightness (0–100), c = chroma. They are
 * gamut-clamped and given an ink colour by `getInterfaceTokens` in oklch.ts.
 * See docs/event-setup-hub-and-design-tokens.md.
 */
import type { AccentKeyframeRow, InterfaceAccents } from './oklch';

/**
 * Hand-picked accents per built-in theme. Without `accent2` the secondary
 * accent comes from the auto curve below.
 */
export const BUILTIN_INTERFACE_ACCENTS: Record<string, InterfaceAccents> = {
  '2016': { accent: { h: 195, l: 80, c: 0.12 } },
  '2017': {
    accent: { h: 22, l: 66, c: 0.2 },
    accent2: { h: 265.6, l: 58, c: 0.167 },
  },
  '2018': { accent: { h: 212.7, l: 79, c: 0.124 } },
  '2019': {
    accent: { h: 252.9, l: 64.1, c: 0.197 },
    accent2: { h: 247, l: 62, c: 0.106 },
  },
  '2020': {
    accent: { h: 265.2, l: 84, c: 0.079 },
    accent2: { h: 263.9, l: 58, c: 0.229 },
  },
  '2021': {
    accent: { h: 343, l: 77, c: 0.187 },
    accent2: { h: 310.2, l: 65.2, c: 0.217 },
  },
  '2022': { accent: { h: 78, l: 66, c: 0.138 } },
  '2023': {
    accent: { h: 105, l: 92, c: 0.29 },
    accent2: { h: 1.1, l: 64.4, c: 0.26 },
  },
  '2024': {
    accent: { h: 335, l: 66, c: 0.24 },
    accent2: { h: 298.8, l: 58, c: 0.195 },
  },
  '2025': {
    accent: { h: 343, l: 66, c: 0.225 },
    accent2: { h: 303, l: 64.7, c: 0.211 },
  },
  '2026': {
    accent: { h: 88, l: 84, c: 0.13 },
    accent2: { h: 101, l: 65, c: 0.105 },
  },
  'JESC-2021': { accent: { h: 30, l: 68, c: 0.17 } },
  'JESC-2022': {
    accent: { h: 88, l: 84, c: 0.13 },
    accent2: { h: 5.8, l: 58, c: 0.21 },
  },
  'JESC-2023': { accent: { h: 198.8, l: 80.1, c: 0.12 } },
  'JESC-2024': {
    accent: { h: 335.8, l: 84, c: 0.128 },
    accent2: { h: 335.9, l: 67.7, c: 0.259 },
  },
  'JESC-2025': {
    accent: { h: 350, l: 66, c: 0.23 },
    accent2: { h: 310, l: 65.1, c: 0.217 },
  },
};

/**
 * Auto-accent curve for custom themes: one row per OKLCH hue of the primary,
 * one stop per custom-theme shade (`primL` = that shade's primary.900
 * lightness). `getAutoAccents` interpolates between rows and stops; a stop
 * without `accent2` uses the hue − 40° rule.
 */
export const ACCENT_KEYFRAMES: AccentKeyframeRow[] = [
  {
    hue: 0,
    stops: [
      { shade: 35, primL: 25.7, accent: { h: 78, l: 74, c: 0.135 } },
      { shade: 60, primL: 36.4, accent: { h: 0.1, l: 84, c: 0.096 } },
      {
        shade: 85,
        primL: 46.3,
        accent: { h: 0.1, l: 84, c: 0.096 },
        accent2: { h: 345, l: 65.5, c: 0.19 },
      },
    ],
  },
  {
    hue: 30,
    stops: [
      {
        shade: 35,
        primL: 26,
        accent: { h: 92, l: 83, c: 0.135 },
        accent2: { h: 61, l: 80.1, c: 0.143 },
      },
      {
        shade: 60,
        primL: 36.5,
        accent: { h: 92, l: 86, c: 0.15 },
        accent2: { h: 45, l: 75, c: 0.134 },
      },
      {
        shade: 85,
        primL: 46.5,
        accent: { h: 92, l: 88, c: 0.15 },
        accent2: { h: 52, l: 72.6, c: 0.15 },
      },
    ],
  },
  {
    hue: 60,
    stops: [
      {
        shade: 35,
        primL: 29.4,
        accent: { h: 88, l: 85, c: 0.099 },
        accent2: { h: 48, l: 55.5, c: 0.172 },
      },
      {
        shade: 60,
        primL: 41.9,
        accent: { h: 88, l: 88, c: 0.11 },
        accent2: { h: 48, l: 56, c: 0.137 },
      },
      {
        shade: 85,
        primL: 53.5,
        accent: { h: 88, l: 90, c: 0.11 },
        accent2: { h: 48, l: 56.5, c: 0.145 },
      },
    ],
  },
  {
    hue: 90,
    stops: [
      {
        shade: 35,
        primL: 32.7,
        accent: { h: 35, l: 67, c: 0.144 },
        accent2: { h: 50, l: 62, c: 0.164 },
      },
      {
        shade: 60,
        primL: 46.8,
        accent: { h: 89.7, l: 84, c: 0.13 },
        accent2: { h: 50, l: 62, c: 0.164 },
      },
      { shade: 85, primL: 59.9, accent: { h: 89.7, l: 84, c: 0.13 } },
    ],
  },
  {
    hue: 120,
    stops: [
      {
        shade: 35,
        primL: 34.9,
        accent: { h: 164.8, l: 81.7, c: 0.139 },
        accent2: { h: 124.8, l: 86.1, c: 0.174 },
      },
      {
        shade: 60,
        primL: 50.3,
        accent: { h: 165.1, l: 81.7, c: 0.138 },
        accent2: { h: 125.1, l: 86, c: 0.174 },
      },
      {
        shade: 85,
        primL: 64.6,
        accent: { h: 165.1, l: 81.7, c: 0.138 },
        accent2: { h: 125.1, l: 86, c: 0.174 },
      },
    ],
  },
  {
    hue: 150,
    stops: [
      {
        shade: 35,
        primL: 32.7,
        accent: { h: 195, l: 80.3, c: 0.122 },
        accent2: { h: 155, l: 81, c: 0.155 },
      },
      {
        shade: 60,
        primL: 47.1,
        accent: { h: 150, l: 84, c: 0.13 },
        accent2: { h: 165, l: 59, c: 0.101 },
      },
      {
        shade: 85,
        primL: 60.4,
        accent: { h: 88, l: 86, c: 0.15 },
        accent2: { h: 128, l: 84.8, c: 0.175 },
      },
    ],
  },
  {
    hue: 180,
    stops: [
      { shade: 35, primL: 33.5, accent: { h: 179.9, l: 84, c: 0.13 } },
      { shade: 60, primL: 48.2, accent: { h: 180.2, l: 84, c: 0.13 } },
      { shade: 85, primL: 61.9, accent: { h: 180.2, l: 84, c: 0.13 } },
    ],
  },
  {
    hue: 210,
    stops: [
      { shade: 35, primL: 31.8, accent: { h: 164.7, l: 81.6, c: 0.139 } },
      { shade: 60, primL: 45.6, accent: { h: 165.2, l: 81.7, c: 0.138 } },
      { shade: 85, primL: 58.4, accent: { h: 165.2, l: 81.7, c: 0.138 } },
    ],
  },
  {
    hue: 240,
    stops: [
      { shade: 35, primL: 28.2, accent: { h: 194.6, l: 80.4, c: 0.122 } },
      { shade: 60, primL: 39.9, accent: { h: 195.3, l: 80.3, c: 0.122 } },
      { shade: 85, primL: 50.8, accent: { h: 195.3, l: 80.3, c: 0.122 } },
    ],
  },
  {
    hue: 270,
    stops: [
      { shade: 35, primL: 22.3, accent: { h: 314.9, l: 65.4, c: 0.221 } },
      { shade: 60, primL: 30.2, accent: { h: 314.9, l: 65.4, c: 0.221 } },
      { shade: 85, primL: 38, accent: { h: 314.9, l: 65.4, c: 0.221 } },
    ],
  },
  {
    hue: 300,
    stops: [
      { shade: 35, primL: 23, accent: { h: 345.2, l: 66, c: 0.224 } },
      { shade: 60, primL: 32.1, accent: { h: 344.8, l: 66, c: 0.224 } },
      { shade: 85, primL: 40.6, accent: { h: 344.8, l: 66, c: 0.224 } },
    ],
  },
  {
    hue: 330,
    stops: [
      { shade: 35, primL: 27.1, accent: { h: 100, l: 85, c: 0.135 } },
      { shade: 60, primL: 38.6, accent: { h: 14.9, l: 66, c: 0.208 } },
      { shade: 85, primL: 49.3, accent: { h: 329.9, l: 84, c: 0.13 } },
    ],
  },
];
