/**
 * Emits the merged per-locale message catalogs as content-hashed static JSON
 * under public/messages/ (gitignored, rebuilt by `prebuild`), plus the
 * committed manifest module src/i18n/messagesManifest.generated.ts that maps
 * each locale to its hashed URL. The client fetches these immutably-cached
 * files instead of receiving the catalog inline in every document
 * (see docs/performance-improvement-plan.md, Part C item 2).
 *
 * Run: yarn gen:messages   (also runs automatically before every build)
 */
import { createHash } from 'crypto';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import path from 'path';

import { deepMergeMessages, SUPPORTED_LOCALES } from '../src/i18n/catalog';

const root = path.join(__dirname, '..');
const messagesDir = path.join(root, 'messages');
const outDir = path.join(root, 'public', 'messages');

const readLocale = (locale: string) =>
  JSON.parse(readFileSync(path.join(messagesDir, `${locale}.json`), 'utf8'));

const en = readLocale('en');

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const entries: string[] = [];

for (const locale of SUPPORTED_LOCALES) {
  const merged =
    locale === 'en' ? en : deepMergeMessages(en, readLocale(locale));
  const content = JSON.stringify(merged);
  const hash = createHash('sha256')
    .update(content, 'utf8')
    .digest('hex')
    .slice(0, 10);

  writeFileSync(path.join(outDir, `${locale}.${hash}.json`), content);
  entries.push(
    `  ${locale}: { url: '/messages/${locale}.${hash}.json', hash: '${hash}' },`,
  );
  console.log(`messages/${locale}.json -> /messages/${locale}.${hash}.json`);
}

const manifestModule = `// AUTO-GENERATED by scripts/generateMessages.ts — do not edit by hand.
// Regenerate with \`yarn gen:messages\` (runs automatically on prebuild, and
// lint-staged regenerates it when messages/*.json change).
// messagesManifest.test.ts fails if this drifts from the message files.
import type { SupportedLocale } from './catalog';

export const MESSAGES_CATALOG: Record<
  SupportedLocale,
  { url: string; hash: string }
> = {
${entries.join('\n')}
};
`;

writeFileSync(
  path.join(root, 'src', 'i18n', 'messagesManifest.generated.ts'),
  manifestModule,
);
console.log(`Wrote manifest for ${SUPPORTED_LOCALES.length} locales`);
