/**
 * Source of `src/theme/interfaceAccents.ts`, generated from the Palette Lab's
 * picks (dev only). The output is Prettier-formatted, so it can replace the
 * file as is.
 */
import type {
  AccentKeyframeRow,
  AccentSpec,
  InterfaceAccents,
} from '@/theme/oklch';

const num = (v: number) => String(Math.round(v * 1000) / 1000);
const spec = ({ h, l, c }: AccentSpec) =>
  `{ h: ${num(Math.round(h * 10) / 10)}, l: ${num(
    Math.round(l * 10) / 10,
  )}, c: ${num(c)} }`;

function builtinEntry(year: string, accents: InterfaceAccents): string {
  const key = `'${year}'`;

  if (!accents.accent2) {
    const line = `  ${key}: { accent: ${spec(accents.accent)} },`;

    if (line.length <= 80) return line;

    return [`  ${key}: {`, `    accent: ${spec(accents.accent)},`, '  },'].join(
      '\n',
    );
  }

  return [
    `  ${key}: {`,
    `    accent: ${spec(accents.accent)},`,
    `    accent2: ${spec(accents.accent2)},`,
    '  },',
  ].join('\n');
}

function stopEntry(stop: AccentKeyframeRow['stops'][number]): string {
  const head = `shade: ${stop.shade}, primL: ${num(
    Math.round(stop.primL * 10) / 10,
  )}`;
  const inline = `      { ${head}, accent: ${spec(stop.accent)} },`;

  if (!stop.accent2 && inline.length <= 80) return inline;

  return [
    '      {',
    `        shade: ${stop.shade},`,
    `        primL: ${num(Math.round(stop.primL * 10) / 10)},`,
    `        accent: ${spec(stop.accent)},`,
    ...(stop.accent2 ? [`        accent2: ${spec(stop.accent2)},`] : []),
    '      },',
  ].join('\n');
}

export function generateInterfaceAccentsSource(
  builtin: Record<string, InterfaceAccents>,
  keyframes: AccentKeyframeRow[],
): string {
  return `/**
 * Interface accents, GENERATED by the Palette Lab (\`/dev/palette-lab\`, dev
 * server only): pick there, press "Copy as TS" and replace this file. Hand
 * edits are fine as long as the shape stays the same.
 *
 * Values are OKLCH: h = hue (deg), l = lightness (0–100), c = chroma. They are
 * gamut-clamped and given an ink colour by \`getInterfaceTokens\` in oklch.ts.
 * See docs/event-setup-hub-and-design-tokens.md.
 */
import type { AccentKeyframeRow, InterfaceAccents } from './oklch';

/**
 * Hand-picked accents per built-in theme. Without \`accent2\` the secondary
 * accent comes from the auto curve below.
 */
export const BUILTIN_INTERFACE_ACCENTS: Record<string, InterfaceAccents> = {
${Object.entries(builtin)
  .map(([year, accents]) => builtinEntry(year, accents))
  .join('\n')}
};

/**
 * Auto-accent curve for custom themes: one row per OKLCH hue of the primary,
 * one stop per custom-theme shade (\`primL\` = that shade's primary.900
 * lightness). \`getAutoAccents\` interpolates between rows and stops; a stop
 * without \`accent2\` uses the hue − 40° rule.
 */
export const ACCENT_KEYFRAMES: AccentKeyframeRow[] = [
${keyframes
  .map((row) =>
    [
      '  {',
      `    hue: ${row.hue},`,
      '    stops: [',
      ...row.stops.map(stopEntry),
      '    ],',
      '  },',
    ].join('\n'),
  )
  .join('\n')}
];
`;
}
